# Generated by Django 4.1.7 on 2023-04-05 19:27

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('music', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='BooksPreferences',
            fields=[
                ('genre', models.IntegerField(primary_key=True, serialize=False)),
                ('usersBitmask', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='FilmsPreferences',
            fields=[
                ('genre', models.IntegerField(primary_key=True, serialize=False)),
                ('usersBitmask', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='MusicPreferences',
            fields=[
                ('genre', models.IntegerField(primary_key=True, serialize=False)),
                ('usersBitmask', django.contrib.postgres.fields.ArrayField(base_field=models.BooleanField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('lastfm', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('passwordhash', models.CharField(max_length=16)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.user')),
                ('subscriptions', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
        migrations.CreateModel(
            name='FavouriteTracks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.track')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='AuthTokens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='', max_length=16)),
                ('type', models.CharField(default='password', max_length=10)),
                ('expiration_date', models.DateTimeField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.account')),
            ],
        ),
    ]
