# Generated by Django 4.1.7 on 2023-03-25 12:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BooksPreferences",
            fields=[
                ("genre", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "usersBitmask",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BooleanField(), size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FilmsPreferences",
            fields=[
                ("genre", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "usersBitmask",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BooleanField(), size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MusicPreferences",
            fields=[
                ("genre", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "usersBitmask",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.BooleanField(), size=None
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "favouriteMusic",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "favouriteFilms",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "favouriteBooks",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.userauth"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscriptions",
            fields=[
                (
                    "id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="users.user",
                    ),
                ),
                (
                    "subscriptions",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), size=None
                    ),
                ),
            ],
        ),
    ]
